import Head from 'next/head';
import Image from 'next/image';
import { css } from '@emotion/react';
import { useRouter } from 'next/router';
import axios from 'axios';

export default function Home() {
  const router = useRouter();
  const handleGetLocation = () => {
    if (typeof navigator !== 'undefined' && navigator.geolocation) {
      navigator.geolocation.getCurrentPosition((position) => {
        const latVal = position.coords.latitude;
        const lngVal = position.coords.longitude;
        axios
          .get(
            `https://nominatim.openstreetmap.org/reverse?format=json&lat=${latVal}&lon=${lngVal}&zoom=18&addressdetails=1`
          )
          .then((res) => {
            const pref = `${res.data.address.state}${res.data.address.city}`;
            router.push(`/result?pref=${pref}&lat=${latVal}&lng=${lngVal}`);
          })
          .catch((err) => {
            console.log('Error occurred while fetching data: ', err);
          });
      });
    } else {
      alert(
        'この端末では位置情報機能が利用できません。「都道府県を選択」から遷移いただくか、位置情報機能をオンにしてください。'
      );
    }
  };
  const Main = css`
    background-color: #a1c6ea;
    position: relative;
    min-height: 100vh;
    overflow: hidden;
    &::before,
    &::after {
      content: '';
      z-index: 1;
      filter: blur(100px);
      position: absolute;
    }
    &::before {
      width: 592px;
      height: 472px;
      left: 165px;
      top: -215px;
      border-radius: 50%;
      background: #629cd5;
      box-shadow: -153px 690px 0 #507dbc;
    }
    &::after {
      content: '';
      width: 517px;
      height: 311px;
      left: -378px;
      top: 139px;
      background: #e7f1fb;
    }
  `;
  const Section = css`
    width: calc(100% - 20px);
    position: absolute;
    z-index: 2;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    margin: 10px auto;
    display: flex;
    justify-content: center;
    align-items: center;
    border-radius: 12px;
    &::before {
      content: '';
      box-sizing: border-box;
      position: absolute;
      width: 903px;
      height: 903px;
      margin: auto;
      top: 24px;
      background: rgba(245, 245, 245, 0.4);
      box-shadow: 10px 5px 60px rgba(0, 0, 0, 0.25);
      backdrop-filter: blur(15px);
      border-radius: 50%;
    }
  `;
  const logoWrap = css`
    position: absolute;
    top: -120px;
    bottom: 0;
    margin: auto;
    text-align: center;
    width: 197px;
    height: 87px;
  `;
  const Paragraph = css`
    font-size: 12px;
    color: #287ccd;
  `;
  const BtnWrap = css`
    margin: 0 auto;
    bottom: 20px;
    position: absolute;
    button {
      z-index: 1;
      color: #fff;
      display: block;
      margin: 0 0 18px;
      width: 320px;
      padding: 20px 0;
      background: linear-gradient(
        45deg,
        rgba(42, 130, 215, 1) 0%,
        rgba(38, 118, 195, 1) 100%
      );
      border: none;
      border-radius: 24px;
      cursor: pointer;
      line-height: 1;
      border: 1px solid #fff;
      &::before {
        content: '';
        box-shadow: 0 0 10px #000;
      }
    }
  `;

  return (
    <>
      <Head>
        <title>Weather Wear | 今日のファッションは天気次第</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main css={Main}>
        <section css={Section}>
          <div css={logoWrap}>
            <h1>
              <Image
                src="/images/logo.png"
                alt="Weather Wear"
                priority={true}
                width={197}
                height={56}
              />
            </h1>
            <p css={Paragraph}>今日のファッションは天気次第</p>
          </div>
          <div css={BtnWrap}>
            <button onClick={handleGetLocation}>位置情報を取得</button>
            <button onClick={() => router.push('/pref')}>都道府県を選択</button>
          </div>
        </section>
      </main>
    </>
  );
}
